<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="6" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-18T18:09:08 IST" name="Suite" finished-at="2025-05-18T18:09:34 IST" duration-ms="26504">
    <groups>
      <group name="Purchase">
        <method signature="StandAloneTest.SubmitOrder(java.util.HashMap)[pri:0, instance:Nova.test.StandAloneTest@7d61eb55]" name="SubmitOrder" class="Nova.test.StandAloneTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2025-05-18T18:09:08 IST" name="Test" finished-at="2025-05-18T18:09:34 IST" duration-ms="26504">
      <class name="Nova.test.ErrorValidation">
        <test-method is-config="true" signature="LaunchDriver()[pri:0, instance:Nova.test.ErrorValidation@2438dcd]" started-at="2025-05-18T18:09:08 IST" name="LaunchDriver" finished-at="2025-05-18T18:09:10 IST" duration-ms="1839" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchDriver -->
        <test-method retried="true" signature="LoginErrorDetails()[pri:0, instance:Nova.test.ErrorValidation@2438dcd]" started-at="2025-05-18T18:09:10 IST" name="LoginErrorDetails" finished-at="2025-05-18T18:09:10 IST" duration-ms="401" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.1] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.1] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Nova.test.ErrorValidation.LoginErrorDetails(ErrorValidation.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorDetails -->
        <test-method is-config="true" signature="EndTest()[pri:0, instance:Nova.test.ErrorValidation@2438dcd]" started-at="2025-05-18T18:09:10 IST" name="EndTest" finished-at="2025-05-18T18:09:10 IST" duration-ms="74" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EndTest -->
        <test-method is-config="true" signature="LaunchDriver()[pri:0, instance:Nova.test.ErrorValidation@2438dcd]" started-at="2025-05-18T18:09:10 IST" name="LaunchDriver" finished-at="2025-05-18T18:09:12 IST" duration-ms="2304" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchDriver -->
        <test-method signature="LoginErrorDetails()[pri:0, instance:Nova.test.ErrorValidation@2438dcd]" started-at="2025-05-18T18:09:12 IST" name="LoginErrorDetails" finished-at="2025-05-18T18:09:13 IST" duration-ms="374" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.1] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.1] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Nova.test.ErrorValidation.LoginErrorDetails(ErrorValidation.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorDetails -->
        <test-method is-config="true" signature="EndTest()[pri:0, instance:Nova.test.ErrorValidation@2438dcd]" started-at="2025-05-18T18:09:13 IST" name="EndTest" finished-at="2025-05-18T18:09:13 IST" duration-ms="80" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EndTest -->
        <test-method is-config="true" signature="LaunchDriver()[pri:0, instance:Nova.test.ErrorValidation@2438dcd]" started-at="2025-05-18T18:09:13 IST" name="LaunchDriver" finished-at="2025-05-18T18:09:16 IST" duration-ms="2392" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchDriver -->
        <test-method signature="ProductErrorDetails()[pri:0, instance:Nova.test.ErrorValidation@2438dcd]" started-at="2025-05-18T18:09:16 IST" name="ProductErrorDetails" finished-at="2025-05-18T18:09:19 IST" duration-ms="2962" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorDetails -->
        <test-method is-config="true" signature="EndTest()[pri:0, instance:Nova.test.ErrorValidation@2438dcd]" started-at="2025-05-18T18:09:19 IST" name="EndTest" finished-at="2025-05-18T18:09:19 IST" duration-ms="93" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EndTest -->
      </class> <!-- Nova.test.ErrorValidation -->
      <class name="Nova.test.StandAloneTest">
        <test-method is-config="true" signature="LaunchDriver()[pri:0, instance:Nova.test.StandAloneTest@7d61eb55]" started-at="2025-05-18T18:09:19 IST" name="LaunchDriver" finished-at="2025-05-18T18:09:21 IST" duration-ms="2219" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchDriver -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:Nova.test.StandAloneTest@7d61eb55]" started-at="2025-05-18T18:09:21 IST" name="SubmitOrder" data-provider="GetData" finished-at="2025-05-18T18:09:25 IST" duration-ms="3885" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{item=ADIDAS ORIGINAL, email=dharanidhar220@gmail.com, Password=Ilovecricket@123}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="EndTest()[pri:0, instance:Nova.test.StandAloneTest@7d61eb55]" started-at="2025-05-18T18:09:25 IST" name="EndTest" finished-at="2025-05-18T18:09:25 IST" duration-ms="120" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EndTest -->
        <test-method is-config="true" signature="LaunchDriver()[pri:0, instance:Nova.test.StandAloneTest@7d61eb55]" started-at="2025-05-18T18:09:25 IST" name="LaunchDriver" finished-at="2025-05-18T18:09:28 IST" duration-ms="3159" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchDriver -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:Nova.test.StandAloneTest@7d61eb55]" started-at="2025-05-18T18:09:28 IST" name="SubmitOrder" data-provider="GetData" finished-at="2025-05-18T18:09:32 IST" duration-ms="3814" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{item=ZARA COAT 3, email=dharanidhar2211@gmail.com, Password=Ilovecricket@123}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="EndTest()[pri:0, instance:Nova.test.StandAloneTest@7d61eb55]" started-at="2025-05-18T18:09:32 IST" name="EndTest" finished-at="2025-05-18T18:09:32 IST" duration-ms="96" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EndTest -->
        <test-method is-config="true" signature="LaunchDriver()[pri:0, instance:Nova.test.StandAloneTest@7d61eb55]" started-at="2025-05-18T18:09:32 IST" name="LaunchDriver" finished-at="2025-05-18T18:09:34 IST" duration-ms="1418" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchDriver -->
        <test-method signature="OrderDetails()[pri:0, instance:Nova.test.StandAloneTest@7d61eb55]" started-at="2025-05-18T18:09:34 IST" name="OrderDetails" finished-at="2025-05-18T18:09:34 IST" depends-on-methods="Nova.test.StandAloneTest.SubmitOrder" duration-ms="663" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderDetails -->
        <test-method is-config="true" signature="EndTest()[pri:0, instance:Nova.test.StandAloneTest@7d61eb55]" started-at="2025-05-18T18:09:34 IST" name="EndTest" finished-at="2025-05-18T18:09:34 IST" duration-ms="66" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EndTest -->
      </class> <!-- Nova.test.StandAloneTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
